version: '2'
services:
    datahipster-app:
        image: datahipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://datahipster-mysql:3306/datahipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    datahipster-mysql:
        extends:
            file: mysql.yml
            service: datahipster-mysql
